[2022-03-08 14:20:10,864][MainThread:10932][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:20:13,608][Thread-1:6192][task_id:collect][views.py:17][INFO][b'\x80\x04\x95\xf4\x08\x00\x00\x00\x00\x00\x00\x8c\x16django.db.models.query\x94\x8c\x08QuerySet\x94\x93\x94)\x81\x94}\x94(\x8c\x05model\x94\x8c\rmysite.models\x94\x8c\x07Article\x94\x93\x94\x8c\x03_db\x94N\x8c\x06_hints\x94}\x94\x8c\x05query\x94\x8c\x1adjango.db.models.sql.query\x94\x8c\x05Query\x94\x93\x94)\x81\x94}\x94(\x8c\x11_constructor_args\x94h\x08\x85\x94}\x94\x86\x94h\x05h\x08\x8c\x0ealias_refcount\x94}\x94(\x8c\x0emysite_article\x94K\x01\x8c\tauth_user\x94K\x00u\x8c\talias_map\x94}\x94(h\x18\x8c#django.db.models.sql.datastructures\x94\x8c\tBaseTable\x94\x93\x94)\x81\x94}\x94(\x8c\ntable_name\x94h\x18\x8c\x0btable_alias\x94h\x18ubh\x19h\x1c\x8c\x04Join\x94\x93\x94)\x81\x94}\x94(h!h\x19\x8c\x0cparent_alias\x94h\x18h"h\x19\x8c\tjoin_type\x94\x8c\nINNER JOIN\x94\x8c\tjoin_cols\x94\x8c\tauthor_id\x94\x8c\x02id\x94\x86\x94\x85\x94\x8c\njoin_field\x94\x8c\x17django.db.models.fields\x94\x8c\x0b_load_field\x94\x93\x94\x8c\x06mysite\x94h\x07\x8c\x06author\x94\x87\x94R\x94\x8c\x08nullable\x94\x89\x8c\x11filtered_relation\x94Nubu\x8c\x10external_aliases\x94}\x94\x8c\ttable_map\x94}\x94(h\x18]\x94h\x18ah\x19]\x94h\x19au\x8c\x0cdefault_cols\x94\x89\x8c\x10default_ordering\x94\x88\x8c\x11standard_ordering\x94\x88\x8c\x0cused_aliases\x94\x8f\x94\x8c\x10filter_is_sticky\x94\x89\x8c\x08subquery\x94\x89\x8c\x06select\x94(\x8c\x1cdjango.db.models.expressions\x94\x8c\x03Col\x94\x93\x94)\x81\x94}\x94(h\x12h\x18h2h3h\x07h,\x87\x94R\x94\x86\x94}\x94\x86\x94\x8c\x0coutput_field\x94hM\x8c\x05alias\x94h\x18\x8c\x06target\x94hMubhI)\x81\x94}\x94(h\x12h\x18h6h2\x8c\x04auth\x94\x8c\x04User\x94h,\x87\x94R\x94\x87\x94}\x94\x86\x94hQhYhRh\x18hSh6ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05title\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhahRh\x18hShaubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04body\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhihRh\x18hShiubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x06create\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhqhRh\x18hShqubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x06update\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhyhRh\x18hShyubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05label\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x81hRh\x18hSh\x81ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04know\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x89hRh\x18hSh\x89ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05state\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x91hRh\x18hSh\x91ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04read\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x99hRh\x18hSh\x99ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x0bpicture_url\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\xa1hRh\x18hSh\xa1ubt\x94\x8c\x05where\x94\x8c\x1adjango.db.models.sql.where\x94\x8c\tWhereNode\x94\x93\x94)\x81\x94}\x94(\x8c\x08children\x94]\x94\x8c\tconnector\x94\x8c\x03AND\x94\x8c\x07negated\x94\x89\x8c\x12contains_aggregate\x94\x89ub\x8c\x0bwhere_class\x94h\xa9\x8c\x08group_by\x94N\x8c\x08order_by\x94\x8c\x05-read\x94\x85\x94\x8c\x08low_mark\x94K\x00\x8c\thigh_mark\x94K\x03\x8c\x08distinct\x94\x89\x8c\x0fdistinct_fields\x94)\x8c\x11select_for_update\x94\x89\x8c\x18select_for_update_nowait\x94\x89\x8c\x1dselect_for_update_skip_locked\x94\x89\x8c\x14select_for_update_of\x94)\x8c\x0eselect_related\x94\x89\x8c\tmax_depth\x94K\x05\x8c\rvalues_select\x94(h,h+h_hghohwh\x7fh\x87h\x8fh\x97h\x9ft\x94\x8c\x0bannotations\x94}\x94\x8c\x16annotation_select_mask\x94N\x8c\x18_annotation_select_cache\x94N\x8c\ncombinator\x94N\x8c\x0ecombinator_all\x94\x89\x8c\x10combined_queries\x94)\x8c\x05extra\x94}\x94\x8c\x11extra_select_mask\x94N\x8c\x13_extra_select_cache\x94N\x8c\x0cextra_tables\x94)\x8c\x0eextra_order_by\x94)\x8c\x10deferred_loading\x94(\x91\x94\x88\x86\x94\x8c\x13_filtered_relations\x94}\x94\x8c\rexplain_query\x94\x89\x8c\x0eexplain_format\x94N\x8c\x0fexplain_options\x94}\x94\x8c\nbase_table\x94h\x18ub\x8c\r_result_cache\x94]\x94\x8c\x0e_sticky_filter\x94\x89\x8c\n_for_write\x94\x89\x8c\x19_prefetch_related_lookups\x94)\x8c\x0e_prefetch_done\x94\x89\x8c\x16_known_related_objects\x94}\x94\x8c\x0f_iterable_class\x94h\x00\x8c\x0eValuesIterable\x94\x93\x94\x8c\x07_fields\x94)\x8c\x0f_django_version\x94\x8c\x053.0.8\x94ub.']
[2022-03-08 14:20:55,473][MainThread:15576][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:20:58,886][Thread-1:27028][task_id:collect][views.py:17][INFO][b'\x80\x04\x95\xf4\x08\x00\x00\x00\x00\x00\x00\x8c\x16django.db.models.query\x94\x8c\x08QuerySet\x94\x93\x94)\x81\x94}\x94(\x8c\x05model\x94\x8c\rmysite.models\x94\x8c\x07Article\x94\x93\x94\x8c\x03_db\x94N\x8c\x06_hints\x94}\x94\x8c\x05query\x94\x8c\x1adjango.db.models.sql.query\x94\x8c\x05Query\x94\x93\x94)\x81\x94}\x94(\x8c\x11_constructor_args\x94h\x08\x85\x94}\x94\x86\x94h\x05h\x08\x8c\x0ealias_refcount\x94}\x94(\x8c\x0emysite_article\x94K\x01\x8c\tauth_user\x94K\x00u\x8c\talias_map\x94}\x94(h\x18\x8c#django.db.models.sql.datastructures\x94\x8c\tBaseTable\x94\x93\x94)\x81\x94}\x94(\x8c\ntable_name\x94h\x18\x8c\x0btable_alias\x94h\x18ubh\x19h\x1c\x8c\x04Join\x94\x93\x94)\x81\x94}\x94(h!h\x19\x8c\x0cparent_alias\x94h\x18h"h\x19\x8c\tjoin_type\x94\x8c\nINNER JOIN\x94\x8c\tjoin_cols\x94\x8c\tauthor_id\x94\x8c\x02id\x94\x86\x94\x85\x94\x8c\njoin_field\x94\x8c\x17django.db.models.fields\x94\x8c\x0b_load_field\x94\x93\x94\x8c\x06mysite\x94h\x07\x8c\x06author\x94\x87\x94R\x94\x8c\x08nullable\x94\x89\x8c\x11filtered_relation\x94Nubu\x8c\x10external_aliases\x94}\x94\x8c\ttable_map\x94}\x94(h\x18]\x94h\x18ah\x19]\x94h\x19au\x8c\x0cdefault_cols\x94\x89\x8c\x10default_ordering\x94\x88\x8c\x11standard_ordering\x94\x88\x8c\x0cused_aliases\x94\x8f\x94\x8c\x10filter_is_sticky\x94\x89\x8c\x08subquery\x94\x89\x8c\x06select\x94(\x8c\x1cdjango.db.models.expressions\x94\x8c\x03Col\x94\x93\x94)\x81\x94}\x94(h\x12h\x18h2h3h\x07h,\x87\x94R\x94\x86\x94}\x94\x86\x94\x8c\x0coutput_field\x94hM\x8c\x05alias\x94h\x18\x8c\x06target\x94hMubhI)\x81\x94}\x94(h\x12h\x18h6h2\x8c\x04auth\x94\x8c\x04User\x94h,\x87\x94R\x94\x87\x94}\x94\x86\x94hQhYhRh\x18hSh6ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05title\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhahRh\x18hShaubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04body\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhihRh\x18hShiubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x06create\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhqhRh\x18hShqubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x06update\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhyhRh\x18hShyubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05label\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x81hRh\x18hSh\x81ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04know\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x89hRh\x18hSh\x89ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05state\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x91hRh\x18hSh\x91ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04read\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x99hRh\x18hSh\x99ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x0bpicture_url\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\xa1hRh\x18hSh\xa1ubt\x94\x8c\x05where\x94\x8c\x1adjango.db.models.sql.where\x94\x8c\tWhereNode\x94\x93\x94)\x81\x94}\x94(\x8c\x08children\x94]\x94\x8c\tconnector\x94\x8c\x03AND\x94\x8c\x07negated\x94\x89\x8c\x12contains_aggregate\x94\x89ub\x8c\x0bwhere_class\x94h\xa9\x8c\x08group_by\x94N\x8c\x08order_by\x94\x8c\x05-read\x94\x85\x94\x8c\x08low_mark\x94K\x00\x8c\thigh_mark\x94K\x03\x8c\x08distinct\x94\x89\x8c\x0fdistinct_fields\x94)\x8c\x11select_for_update\x94\x89\x8c\x18select_for_update_nowait\x94\x89\x8c\x1dselect_for_update_skip_locked\x94\x89\x8c\x14select_for_update_of\x94)\x8c\x0eselect_related\x94\x89\x8c\tmax_depth\x94K\x05\x8c\rvalues_select\x94(h,h+h_hghohwh\x7fh\x87h\x8fh\x97h\x9ft\x94\x8c\x0bannotations\x94}\x94\x8c\x16annotation_select_mask\x94N\x8c\x18_annotation_select_cache\x94N\x8c\ncombinator\x94N\x8c\x0ecombinator_all\x94\x89\x8c\x10combined_queries\x94)\x8c\x05extra\x94}\x94\x8c\x11extra_select_mask\x94N\x8c\x13_extra_select_cache\x94N\x8c\x0cextra_tables\x94)\x8c\x0eextra_order_by\x94)\x8c\x10deferred_loading\x94(\x91\x94\x88\x86\x94\x8c\x13_filtered_relations\x94}\x94\x8c\rexplain_query\x94\x89\x8c\x0eexplain_format\x94N\x8c\x0fexplain_options\x94}\x94\x8c\nbase_table\x94h\x18ub\x8c\r_result_cache\x94]\x94\x8c\x0e_sticky_filter\x94\x89\x8c\n_for_write\x94\x89\x8c\x19_prefetch_related_lookups\x94)\x8c\x0e_prefetch_done\x94\x89\x8c\x16_known_related_objects\x94}\x94\x8c\x0f_iterable_class\x94h\x00\x8c\x0eValuesIterable\x94\x93\x94\x8c\x07_fields\x94)\x8c\x0f_django_version\x94\x8c\x053.0.8\x94ub.']
[2022-03-08 14:21:08,664][Thread-1:27028][task_id:collect][views.py:17][INFO][b'\x80\x04\x95\xf4\x08\x00\x00\x00\x00\x00\x00\x8c\x16django.db.models.query\x94\x8c\x08QuerySet\x94\x93\x94)\x81\x94}\x94(\x8c\x05model\x94\x8c\rmysite.models\x94\x8c\x07Article\x94\x93\x94\x8c\x03_db\x94N\x8c\x06_hints\x94}\x94\x8c\x05query\x94\x8c\x1adjango.db.models.sql.query\x94\x8c\x05Query\x94\x93\x94)\x81\x94}\x94(\x8c\x11_constructor_args\x94h\x08\x85\x94}\x94\x86\x94h\x05h\x08\x8c\x0ealias_refcount\x94}\x94(\x8c\x0emysite_article\x94K\x01\x8c\tauth_user\x94K\x00u\x8c\talias_map\x94}\x94(h\x18\x8c#django.db.models.sql.datastructures\x94\x8c\tBaseTable\x94\x93\x94)\x81\x94}\x94(\x8c\ntable_name\x94h\x18\x8c\x0btable_alias\x94h\x18ubh\x19h\x1c\x8c\x04Join\x94\x93\x94)\x81\x94}\x94(h!h\x19\x8c\x0cparent_alias\x94h\x18h"h\x19\x8c\tjoin_type\x94\x8c\nINNER JOIN\x94\x8c\tjoin_cols\x94\x8c\tauthor_id\x94\x8c\x02id\x94\x86\x94\x85\x94\x8c\njoin_field\x94\x8c\x17django.db.models.fields\x94\x8c\x0b_load_field\x94\x93\x94\x8c\x06mysite\x94h\x07\x8c\x06author\x94\x87\x94R\x94\x8c\x08nullable\x94\x89\x8c\x11filtered_relation\x94Nubu\x8c\x10external_aliases\x94}\x94\x8c\ttable_map\x94}\x94(h\x18]\x94h\x18ah\x19]\x94h\x19au\x8c\x0cdefault_cols\x94\x89\x8c\x10default_ordering\x94\x88\x8c\x11standard_ordering\x94\x88\x8c\x0cused_aliases\x94\x8f\x94\x8c\x10filter_is_sticky\x94\x89\x8c\x08subquery\x94\x89\x8c\x06select\x94(\x8c\x1cdjango.db.models.expressions\x94\x8c\x03Col\x94\x93\x94)\x81\x94}\x94(h\x12h\x18h2h3h\x07h,\x87\x94R\x94\x86\x94}\x94\x86\x94\x8c\x0coutput_field\x94hM\x8c\x05alias\x94h\x18\x8c\x06target\x94hMubhI)\x81\x94}\x94(h\x12h\x18h6h2\x8c\x04auth\x94\x8c\x04User\x94h,\x87\x94R\x94\x87\x94}\x94\x86\x94hQhYhRh\x18hSh6ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05title\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhahRh\x18hShaubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04body\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhihRh\x18hShiubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x06create\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhqhRh\x18hShqubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x06update\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQhyhRh\x18hShyubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05label\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x81hRh\x18hSh\x81ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04know\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x89hRh\x18hSh\x89ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x05state\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x91hRh\x18hSh\x91ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x04read\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\x99hRh\x18hSh\x99ubhI)\x81\x94}\x94(h\x12h\x18h2h3h\x07\x8c\x0bpicture_url\x94\x87\x94R\x94\x86\x94}\x94\x86\x94hQh\xa1hRh\x18hSh\xa1ubt\x94\x8c\x05where\x94\x8c\x1adjango.db.models.sql.where\x94\x8c\tWhereNode\x94\x93\x94)\x81\x94}\x94(\x8c\x08children\x94]\x94\x8c\tconnector\x94\x8c\x03AND\x94\x8c\x07negated\x94\x89\x8c\x12contains_aggregate\x94\x89ub\x8c\x0bwhere_class\x94h\xa9\x8c\x08group_by\x94N\x8c\x08order_by\x94\x8c\x05-read\x94\x85\x94\x8c\x08low_mark\x94K\x00\x8c\thigh_mark\x94K\x03\x8c\x08distinct\x94\x89\x8c\x0fdistinct_fields\x94)\x8c\x11select_for_update\x94\x89\x8c\x18select_for_update_nowait\x94\x89\x8c\x1dselect_for_update_skip_locked\x94\x89\x8c\x14select_for_update_of\x94)\x8c\x0eselect_related\x94\x89\x8c\tmax_depth\x94K\x05\x8c\rvalues_select\x94(h,h+h_hghohwh\x7fh\x87h\x8fh\x97h\x9ft\x94\x8c\x0bannotations\x94}\x94\x8c\x16annotation_select_mask\x94N\x8c\x18_annotation_select_cache\x94N\x8c\ncombinator\x94N\x8c\x0ecombinator_all\x94\x89\x8c\x10combined_queries\x94)\x8c\x05extra\x94}\x94\x8c\x11extra_select_mask\x94N\x8c\x13_extra_select_cache\x94N\x8c\x0cextra_tables\x94)\x8c\x0eextra_order_by\x94)\x8c\x10deferred_loading\x94(\x91\x94\x88\x86\x94\x8c\x13_filtered_relations\x94}\x94\x8c\rexplain_query\x94\x89\x8c\x0eexplain_format\x94N\x8c\x0fexplain_options\x94}\x94\x8c\nbase_table\x94h\x18ub\x8c\r_result_cache\x94]\x94\x8c\x0e_sticky_filter\x94\x89\x8c\n_for_write\x94\x89\x8c\x19_prefetch_related_lookups\x94)\x8c\x0e_prefetch_done\x94\x89\x8c\x16_known_related_objects\x94}\x94\x8c\x0f_iterable_class\x94h\x00\x8c\x0eValuesIterable\x94\x93\x94\x8c\x07_fields\x94)\x8c\x0f_django_version\x94\x8c\x053.0.8\x94ub.']
[2022-03-08 14:27:46,586][MainThread:15576][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\urls.py changed, reloading.]
[2022-03-08 14:27:47,408][MainThread:3820][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:28:50,741][MainThread:9204][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:32:54,822][MainThread:19116][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:33:12,373][MainThread:13180][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:35:51,555][MainThread:172][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:35:54,095][Thread-1:18644][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 17, in index
    logger.info(str(RedisConnection.get('hotarticle').__dict__))
AttributeError: 'bytes' object has no attribute '__dict__'
[2022-03-08 14:36:49,280][MainThread:172][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:36:50,107][MainThread:13024][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:36:51,149][Thread-1:21320][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 17, in index
    logger.info(str(RedisConnection.get('hotarticle').encode("utf-8")))
AttributeError: 'bytes' object has no attribute 'encode'
[2022-03-08 14:37:02,117][MainThread:13024][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:37:02,981][MainThread:22140][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:37:03,417][Thread-1:3244][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 17, in index
    logger.info(str(RedisConnection.get('hotarticle').decode("utf-8")))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
[2022-03-08 14:37:31,461][MainThread:22140][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:37:32,256][MainThread:16656][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:37:32,447][Thread-1:26296][task_id:collect][views.py:17][INFO][<QuerySet []>]
[2022-03-08 14:37:46,583][MainThread:16656][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:37:47,413][MainThread:16304][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:37:50,669][Thread-1:3084][task_id:collect][views.py:17][INFO][{'model': <class 'mysite.models.Article'>, '_db': None, '_hints': {}, 'query': <django.db.models.sql.query.Query object at 0x00000195475C39A0>, '_result_cache': [], '_sticky_filter': False, '_for_write': False, '_prefetch_related_lookups': (), '_prefetch_done': False, '_known_related_objects': {}, '_iterable_class': <class 'django.db.models.query.ValuesIterable'>, '_fields': (), '_django_version': '3.0.8'}]
[2022-03-08 14:38:11,172][MainThread:16304][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:38:12,013][MainThread:25228][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:38:12,902][Thread-1:468][task_id:collect][views.py:17][INFO][{'_constructor_args': ((<class 'mysite.models.Article'>,), {}), 'model': <class 'mysite.models.Article'>, 'alias_refcount': {'mysite_article': 1, 'auth_user': 0}, 'alias_map': {'mysite_article': <django.db.models.sql.datastructures.BaseTable object at 0x000001A219B76790>, 'auth_user': <django.db.models.sql.datastructures.Join object at 0x000001A219B764C0>}, 'external_aliases': {}, 'table_map': {'mysite_article': ['mysite_article'], 'auth_user': ['auth_user']}, 'default_cols': False, 'default_ordering': True, 'standard_ordering': True, 'used_aliases': set(), 'filter_is_sticky': False, 'subquery': False, 'select': (Col(mysite_article, mysite.Article.id), Col(mysite_article, mysite.Article.author), Col(mysite_article, mysite.Article.title), Col(mysite_article, mysite.Article.body), Col(mysite_article, mysite.Article.create), Col(mysite_article, mysite.Article.update), Col(mysite_article, mysite.Article.label), Col(mysite_article, mysite.Article.know), Col(mysite_article, mysite.Article.state), Col(mysite_article, mysite.Article.read), Col(mysite_article, mysite.Article.picture_url)), 'where': <WhereNode: (AND: )>, 'where_class': <class 'django.db.models.sql.where.WhereNode'>, 'group_by': None, 'order_by': ('-read',), 'low_mark': 0, 'high_mark': 3, 'distinct': False, 'distinct_fields': (), 'select_for_update': False, 'select_for_update_nowait': False, 'select_for_update_skip_locked': False, 'select_for_update_of': (), 'select_related': False, 'max_depth': 5, 'values_select': ('id', 'author_id', 'title', 'body', 'create', 'update', 'label', 'know', 'state', 'read', 'picture_url'), 'annotations': {}, 'annotation_select_mask': None, '_annotation_select_cache': None, 'combinator': None, 'combinator_all': False, 'combined_queries': (), 'extra': {}, 'extra_select_mask': None, '_extra_select_cache': None, 'extra_tables': (), 'extra_order_by': (), 'deferred_loading': (frozenset(), True), '_filtered_relations': {}, 'explain_query': False, 'explain_format': None, 'explain_options': {}, 'base_table': 'mysite_article'}]
[2022-03-08 14:38:20,529][MainThread:5596][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:38:22,807][Thread-1:20928][task_id:collect][views.py:17][INFO][{'_constructor_args': ((<class 'mysite.models.Article'>,), {}), 'model': <class 'mysite.models.Article'>, 'alias_refcount': {'mysite_article': 1, 'auth_user': 0}, 'alias_map': {'mysite_article': <django.db.models.sql.datastructures.BaseTable object at 0x000001DA084B0550>, 'auth_user': <django.db.models.sql.datastructures.Join object at 0x000001DA084B0280>}, 'external_aliases': {}, 'table_map': {'mysite_article': ['mysite_article'], 'auth_user': ['auth_user']}, 'default_cols': False, 'default_ordering': True, 'standard_ordering': True, 'used_aliases': set(), 'filter_is_sticky': False, 'subquery': False, 'select': (Col(mysite_article, mysite.Article.id), Col(mysite_article, mysite.Article.author), Col(mysite_article, mysite.Article.title), Col(mysite_article, mysite.Article.body), Col(mysite_article, mysite.Article.create), Col(mysite_article, mysite.Article.update), Col(mysite_article, mysite.Article.label), Col(mysite_article, mysite.Article.know), Col(mysite_article, mysite.Article.state), Col(mysite_article, mysite.Article.read), Col(mysite_article, mysite.Article.picture_url)), 'where': <WhereNode: (AND: )>, 'where_class': <class 'django.db.models.sql.where.WhereNode'>, 'group_by': None, 'order_by': ('-read',), 'low_mark': 0, 'high_mark': 3, 'distinct': False, 'distinct_fields': (), 'select_for_update': False, 'select_for_update_nowait': False, 'select_for_update_skip_locked': False, 'select_for_update_of': (), 'select_related': False, 'max_depth': 5, 'values_select': ('id', 'author_id', 'title', 'body', 'create', 'update', 'label', 'know', 'state', 'read', 'picture_url'), 'annotations': {}, 'annotation_select_mask': None, '_annotation_select_cache': None, 'combinator': None, 'combinator_all': False, 'combined_queries': (), 'extra': {}, 'extra_select_mask': None, '_extra_select_cache': None, 'extra_tables': (), 'extra_order_by': (), 'deferred_loading': (frozenset(), True), '_filtered_relations': {}, 'explain_query': False, 'explain_format': None, 'explain_options': {}, 'base_table': 'mysite_article'}]
[2022-03-08 14:43:37,213][MainThread:5596][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:43:38,022][MainThread:23532][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:43:39,183][Thread-1:18008][task_id:collect][views.py:17][INFO][0]
[2022-03-08 14:46:35,387][MainThread:23532][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:46:36,191][MainThread:14352][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:57:58,074][MainThread:14352][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:57:58,858][MainThread:16764][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 14:59:21,376][MainThread:16764][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 14:59:22,160][MainThread:21608][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 15:02:52,344][MainThread:21608][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\admin.py changed, reloading.]
[2022-03-08 15:02:53,138][MainThread:17752][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 15:17:42,402][MainThread:17752][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 15:17:43,167][MainThread:8056][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 15:20:42,741][MainThread:18564][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 22:39:37,618][MainThread:16256][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 22:40:08,126][MainThread:11428][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 22:40:22,061][Thread-1:3296][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 15, in index
    RedisConnection = get_redis_connection('default')
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django_redis\__init__.py", line 15, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature
[2022-03-08 22:40:22,204][Thread-1:3296][task_id:django.request][log.py:222][WARNING][Not Found: /favicon.ico]
[2022-03-08 22:43:14,740][MainThread:11428][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-08 22:43:15,473][MainThread:10612][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 22:43:16,993][Thread-1:13416][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django_redis\__init__.py", line 15, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature
[2022-03-08 22:45:01,921][Thread-1:13416][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django_redis\__init__.py", line 15, in get_redis_connection
    raise NotImplementedError("This backend does not support this feature")
NotImplementedError: This backend does not support this feature
[2022-03-08 22:47:39,612][MainThread:15548][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-08 22:47:42,463][Thread-1:12748][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
TypeError: a bytes-like object is required, not 'NoneType'
[2022-03-08 22:47:43,470][Thread-1:12748][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
TypeError: a bytes-like object is required, not 'NoneType'
[2022-03-08 22:47:44,213][Thread-1:12748][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 16, in index
    logger.info(len(pickle.loads(get_redis_connection('default').get('hotarticle'))))
TypeError: a bytes-like object is required, not 'NoneType'
[2022-03-09 19:55:35,135][MainThread:27640][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 19:55:38,652][Thread-1:17568][task_id:django.request][log.py:222][WARNING][Not Found: /favicon.ico]
[2022-03-09 19:55:56,969][Thread-1:17568][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 19:55:56,985][Thread-1:17568][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 19:55:59,138][Thread-1:17568][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 19:55:59,139][Thread-2:25836][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:00:47,303][MainThread:27640][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\urls.py changed, reloading.]
[2022-03-09 20:00:48,083][MainThread:13132][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:00:48,397][Thread-1:1304][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 20:00:48,401][Thread-1:1304][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:00:56,074][Thread-1:1304][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 20:00:56,076][Thread-2:27472][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:13:51,351][Thread-4:24208][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/1.png]
[2022-03-09 20:14:10,556][Thread-4:24208][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/1.jpg]
[2022-03-09 20:14:13,539][Thread-4:24208][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/1.jpg]
[2022-03-09 20:21:20,865][MainThread:19684][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:22:02,960][Thread-1:20312][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:22:02,960][Thread-2:19188][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 20:26:57,702][Thread-2:19188][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/1.jpg]
[2022-03-09 20:32:28,518][MainThread:19684][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\urls.py changed, reloading.]
[2022-03-09 20:32:29,316][MainThread:21488][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:32:32,905][MainThread:21488][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\urls.py changed, reloading.]
[2022-03-09 20:32:33,659][MainThread:18900][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:32:45,615][MainThread:18764][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:32:50,374][Thread-1:23548][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/1.jpg]
[2022-03-09 20:32:55,781][Thread-1:23548][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 20:32:55,782][Thread-2:26516][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:39:53,735][MainThread:5388][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:39:59,099][Thread-2:23852][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:39:59,100][Thread-1:1956][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 20:40:01,289][Thread-1:1956][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 20:40:01,290][Thread-2:23852][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:40:01,990][Thread-2:23852][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/message.png]
[2022-03-09 20:40:01,991][Thread-1:1956][task_id:django.request][log.py:222][WARNING][Not Found: /static/js/pagecomment.js]
[2022-03-09 20:40:17,108][Thread-2:23852][task_id:django.request][log.py:222][WARNING][Not Found: /static/image/1.jpg]
[2022-03-09 20:42:13,030][MainThread:21480][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:42:29,951][MainThread:22516][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:42:37,658][Thread-1:18732][task_id:django.request][log.py:222][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
TypeError: 'FileSystemFinder' object is not callable
[2022-03-09 20:42:47,974][MainThread:22516][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-09 20:42:48,746][MainThread:19996][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:42:52,970][MainThread:9288][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:44:41,002][MainThread:26324][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:51:07,808][MainThread:26324][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-09 20:51:08,576][MainThread:17112][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 20:51:43,222][MainThread:17112][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-09 20:51:43,968][MainThread:17556][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 21:21:51,980][MainThread:27560][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 21:22:27,240][MainThread:20648][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 21:22:52,328][MainThread:7996][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 21:24:44,491][MainThread:4508][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-09 21:30:13,080][MainThread:24164][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 18:37:24,148][MainThread:23228][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 18:37:39,176][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /favicon.ico]
[2022-03-10 18:37:45,617][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/base.css]
[2022-03-10 18:37:45,619][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/login.css]
[2022-03-10 18:37:45,621][Thread-3:26960][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:38:33,157][Thread-3:26960][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/base.css]
[2022-03-10 18:38:33,159][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/dashboard.css]
[2022-03-10 18:38:33,160][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:38:39,544][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/base.css]
[2022-03-10 18:38:39,545][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/changelists.css]
[2022-03-10 18:38:39,548][Thread-4:2760][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/vendor/jquery/jquery.min.js]
[2022-03-10 18:38:39,549][Thread-5:2512][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/jquery.init.js]
[2022-03-10 18:38:39,551][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:38:39,554][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/admin/RelatedObjectLookups.js]
[2022-03-10 18:38:39,555][Thread-4:2760][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/actions.min.js]
[2022-03-10 18:38:39,556][Thread-6:5160][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/core.js]
[2022-03-10 18:38:39,559][Thread-5:2512][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/urlify.js]
[2022-03-10 18:38:39,561][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/prepopulate.min.js]
[2022-03-10 18:38:39,563][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js]
[2022-03-10 18:38:39,573][Thread-3:26960][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:38:40,638][Thread-3:26960][task_id:django.request][log.py:222][ERROR][Internal Server Error: /admin/mysite/article/add/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 992, in render
    return render_value_in_context(output, context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 971, in render_value_in_context
    value = str(value)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\html.py", line 373, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 92, in as_widget
    return widget.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\ckeditor\widgets.py", line 114, in render
    renderer.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 30, in render
    template = self.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 36, in get_template
    return self.engine.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html
[2022-03-10 18:40:18,530][Thread-3:26960][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/base.css]
[2022-03-10 18:40:18,531][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/changelists.css]
[2022-03-10 18:40:18,533][Thread-5:2512][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/vendor/jquery/jquery.min.js]
[2022-03-10 18:40:18,534][Thread-6:5160][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/jquery.init.js]
[2022-03-10 18:40:18,535][Thread-4:2760][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/core.js]
[2022-03-10 18:40:18,539][Thread-3:26960][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:40:18,540][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/admin/RelatedObjectLookups.js]
[2022-03-10 18:40:18,543][Thread-5:2512][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/actions.min.js]
[2022-03-10 18:40:18,544][Thread-6:5160][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/urlify.js]
[2022-03-10 18:40:18,547][Thread-7:24184][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/prepopulate.min.js]
[2022-03-10 18:40:18,548][Thread-3:26960][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js]
[2022-03-10 18:40:18,558][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:40:21,545][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/base.css]
[2022-03-10 18:40:21,546][Thread-7:24184][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/forms.css]
[2022-03-10 18:40:21,549][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/vendor/jquery/jquery.min.js]
[2022-03-10 18:40:21,551][Thread-8:14268][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/core.js]
[2022-03-10 18:40:21,553][Thread-9:7044][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/actions.min.js]
[2022-03-10 18:40:21,554][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:40:21,556][Thread-7:24184][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/jquery.init.js]
[2022-03-10 18:40:21,558][Thread-1:1692][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js]
[2022-03-10 18:40:21,560][Thread-8:14268][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/admin/RelatedObjectLookups.js]
[2022-03-10 18:40:21,560][Thread-9:7044][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/urlify.js]
[2022-03-10 18:40:21,562][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/prepopulate.min.js]
[2022-03-10 18:40:21,569][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/change_form.js]
[2022-03-10 18:40:21,573][Thread-2:15156][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/prepopulate_init.js]
[2022-03-10 18:40:21,574][Thread-6:5160][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/img/icon-changelink.svg]
[2022-03-10 18:40:21,575][Thread-8:14268][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/img/icon-addlink.svg]
[2022-03-10 18:40:21,576][Thread-7:24184][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/css/responsive.css]
[2022-03-10 18:40:23,244][Thread-7:24184][task_id:django.request][log.py:222][WARNING][Not Found: /static/admin/js/urlify.js]
[2022-03-10 18:40:38,366][MainThread:13184][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 18:40:44,576][Thread-2:9972][task_id:django.request][log.py:222][ERROR][Internal Server Error: /admin/mysite/article/add/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 992, in render
    return render_value_in_context(output, context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 971, in render_value_in_context
    value = str(value)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\html.py", line 373, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 92, in as_widget
    return widget.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\ckeditor\widgets.py", line 114, in render
    renderer.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 30, in render
    template = self.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 36, in get_template
    return self.engine.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html
[2022-03-10 18:48:04,513][MainThread:11140][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 18:48:24,525][Thread-1:20872][task_id:django.request][log.py:222][ERROR][Internal Server Error: /admin/mysite/article/add/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 992, in render
    return render_value_in_context(output, context)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\base.py", line 971, in render_value_in_context
    value = str(value)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\html.py", line 373, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\boundfield.py", line 92, in as_widget
    return widget.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\ckeditor\widgets.py", line 114, in render
    renderer.render(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 30, in render
    template = self.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\forms\renderers.py", line 36, in get_template
    return self.engine.get_template(template_name)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 36, in get_template
    reraise(exc, self)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: ckeditor/widget.html
[2022-03-10 18:50:26,551][MainThread:20088][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 18:50:52,504][MainThread:20088][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-10 18:50:53,286][MainThread:15244][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 19:03:13,284][MainThread:15244][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-10 19:03:14,093][MainThread:27092][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 19:05:33,904][Thread-4:24708][task_id:django.request][log.py:222][WARNING][Not Found: /media/]
[2022-03-10 19:05:36,568][Thread-4:24708][task_id:django.request][log.py:222][ERROR][Internal Server Error: /read/1/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 34, in read
    comments = TComment.objects.filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1354, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1254, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1486, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'article_id' into field. Choices are: body, child_comments, create, id, level, lft, parent, parent_id, reply_to, reply_to_id, rght, tree_id, user, user_id
[2022-03-10 19:05:52,556][Thread-4:24708][task_id:django.request][log.py:222][ERROR][Internal Server Error: /read/1/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\mysite\views.py", line 34, in read
    comments = TComment.objects.filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1354, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1254, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\db\models\sql\query.py", line 1486, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'article_id' into field. Choices are: body, child_comments, create, id, level, lft, parent, parent_id, reply_to, reply_to_id, rght, tree_id, user, user_id
[2022-03-10 19:11:25,181][MainThread:27092][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\mysite\views.py changed, reloading.]
[2022-03-10 19:11:25,953][MainThread:10564][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 19:11:43,084][Thread-1:16036][task_id:django.request][log.py:222][ERROR][Internal Server Error: /comment/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\django_blog-master\django_blog-master\comment\views.py", line 15, in comment
    models.Comment.objects.create(article_id=article_id, parent_id=parent, reply_to_id=reply_to, user_id=user,
AttributeError: module 'comment.models' has no attribute 'Comment'
[2022-03-10 19:13:19,070][MainThread:10564][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\comment\views.py changed, reloading.]
[2022-03-10 19:13:19,832][MainThread:21948][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 19:14:38,440][MainThread:21948][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\comment\views.py changed, reloading.]
[2022-03-10 19:14:39,202][MainThread:20896][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 19:15:17,483][MainThread:20896][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\comment\views.py changed, reloading.]
[2022-03-10 19:15:18,238][MainThread:24192][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 19:18:55,500][MainThread:24192][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-10 19:18:56,272][MainThread:11104][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:14:26,110][MainThread:11104][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-10 20:14:26,889][MainThread:24904][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:15:25,326][MainThread:24904][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\myblog\settings.py changed, reloading.]
[2022-03-10 20:15:26,050][MainThread:21344][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:21:43,375][MainThread:23936][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:25:02,015][MainThread:16524][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:25:37,671][MainThread:20220][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:27:24,633][MainThread:22200][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:46:05,032][MainThread:8044][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:46:21,887][Thread-1:18524][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 20:46:48,920][MainThread:8044][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:46:49,696][MainThread:11872][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:46:49,946][Thread-1:25232][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 20:47:07,898][MainThread:11872][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:47:08,626][MainThread:23696][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:47:09,286][Thread-1:1472][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 20:47:29,043][MainThread:23696][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:47:29,776][MainThread:15676][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:47:30,120][Thread-1:23788][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 20:48:16,923][MainThread:15676][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:48:17,708][MainThread:10824][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:48:17,935][Thread-1:9004][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 20:49:37,313][MainThread:10824][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:49:38,048][MainThread:15744][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:49:38,745][Thread-1:264][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 20, in send_mobile_msg
    message, phone = data.get("meassage"), data.get("phone")
AttributeError: 'bytes' object has no attribute 'get'
[2022-03-10 20:50:04,019][MainThread:15744][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:50:04,746][MainThread:10156][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:50:05,378][Thread-1:15608][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    raise ValueError(
ValueError: The view openapi.views.send_mobile_msg didn't return an HttpResponse object. It returned None instead.
[2022-03-10 20:52:43,534][Thread-1:15608][task_id:django.security.csrf][log.py:222][WARNING][Forbidden (CSRF cookie not set.): /api/sendMessage/]
[2022-03-10 20:53:08,823][MainThread:10156][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:53:09,564][MainThread:24384][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:53:10,287][Thread-1:2224][task_id:django.security.csrf][log.py:222][WARNING][Forbidden (CSRF cookie not set.): /api/sendMessage/]
[2022-03-10 20:54:12,423][Thread-1:2224][task_id:django.security.csrf][log.py:222][WARNING][Forbidden (CSRF cookie not set.): /api/sendMessage/]
[2022-03-10 20:54:33,477][MainThread:24384][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:54:34,198][MainThread:13980][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 20:58:55,192][MainThread:13980][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 20:58:55,941][MainThread:11860][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:06:21,323][MainThread:11860][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\urls.py changed, reloading.]
[2022-03-10 21:06:22,079][MainThread:18000][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:06:36,757][Thread-1:17440][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:07:05,535][Thread-1:17440][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken/]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:07:12,061][MainThread:21544][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:07:34,648][MainThread:21544][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\urls.py changed, reloading.]
[2022-03-10 21:07:35,429][MainThread:20624][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:07:36,213][Thread-1:26576][task_id:django.request][log.py:222][WARNING][Not Found: /api/getToken/]
[2022-03-10 21:07:40,083][Thread-1:26576][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:07:40,942][Thread-1:26576][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:07:54,825][MainThread:20624][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:07:55,601][MainThread:17428][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:07:56,259][Thread-1:21348][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:09:28,281][Thread-1:21348][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:10:16,617][MainThread:17428][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:10:17,359][MainThread:19016][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:10:59,507][MainThread:19016][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:11:00,234][MainThread:19676][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:11:35,823][MainThread:19676][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:11:36,600][MainThread:5804][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:11:37,289][Thread-1:19036][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:11:48,091][MainThread:5804][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:11:48,844][MainThread:12256][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:11:49,373][Thread-1:15632][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/getToken]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:12:32,508][MainThread:12256][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:12:33,284][MainThread:11064][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:14:06,839][Thread-1:18844][task_id:django.request][log.py:222][WARNING][Not Found: /api/sendMessage/]
[2022-03-10 21:14:15,795][Thread-1:18844][task_id:django.security.csrf][log.py:222][WARNING][Forbidden (CSRF token missing or incorrect.): /api/sendMessage]
[2022-03-10 21:15:07,012][Thread-1:18844][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 33, in send_mobile_msg
    message, phone = data.get("meassage"), data.get("phone")
AttributeError: 'bytes' object has no attribute 'get'
[2022-03-10 21:15:59,119][MainThread:11064][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:15:59,871][MainThread:23184][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:16:25,930][Thread-1:8812][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 32, in send_mobile_msg
    message, phone = data.get("meassage"), data.get("phone")
AttributeError: 'bytes' object has no attribute 'get'
[2022-03-10 21:17:26,255][MainThread:23184][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:17:27,015][MainThread:17052][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:17:27,452][Thread-1:19752][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\utils\deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:17:55,251][MainThread:17052][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:17:55,996][MainThread:20700][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:18:14,142][MainThread:20700][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:18:14,890][MainThread:12912][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:18:49,746][MainThread:12912][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:18:50,490][MainThread:24288][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:18:51,489][Thread-1:22312][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 39, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:19:24,397][Thread-1:22312][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 39, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:19:36,656][Thread-1:22312][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 39, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:20:04,425][MainThread:24288][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:20:05,199][MainThread:13180][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:22:41,134][Thread-1:9584][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 36, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:22:56,115][MainThread:13180][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:22:56,860][MainThread:14884][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:22:57,742][Thread-1:22112][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 36, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:23:11,564][Thread-1:22112][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 36, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:23:38,551][MainThread:14884][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:23:39,299][MainThread:16748][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:23:39,998][Thread-1:11340][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 37, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:24:05,325][MainThread:16748][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:24:06,083][MainThread:21808][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:24:07,299][Thread-1:9576][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 36, in send_mobile_msg
    print(rep.get("result").get("success"))
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:24:14,283][Thread-1:9576][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 36, in send_mobile_msg
    print(rep.get("result").get("success"))
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:24:46,678][MainThread:21808][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:24:47,432][MainThread:19096][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:24:48,154][Thread-1:17532][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 37, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:25:32,401][MainThread:19096][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:25:33,135][MainThread:6044][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:25:34,106][Thread-1:11160][task_id:django.request][log.py:222][ERROR][Internal Server Error: /api/sendMessage]
Traceback (most recent call last):
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\django_blog-master\django_blog-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\django_blog-master\django_blog-master\openapi\views.py", line 37, in send_mobile_msg
    if rep.get("result").get("success") is not True:
AttributeError: 'str' object has no attribute 'get'
[2022-03-10 21:26:33,805][MainThread:6044][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\django_blog-master\django_blog-master\openapi\views.py changed, reloading.]
[2022-03-10 21:26:34,561][MainThread:3708][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:29:50,668][Thread-1:7240][task_id:django.request][log.py:222][WARNING][Not Found: /media/]
[2022-03-10 21:30:36,464][MainThread:24260][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:30:38,209][Thread-1:19956][task_id:django.request][log.py:222][WARNING][Not Found: /article/]
[2022-03-10 21:30:39,318][Thread-1:19956][task_id:django.request][log.py:222][WARNING][Not Found: /article/]
[2022-03-10 21:30:40,192][Thread-1:19956][task_id:django.request][log.py:222][WARNING][Not Found: /article/]
[2022-03-10 21:30:41,007][Thread-1:19956][task_id:django.request][log.py:222][WARNING][Not Found: /article/]
[2022-03-10 21:30:41,730][Thread-1:19956][task_id:django.request][log.py:222][WARNING][Not Found: /article/]
[2022-03-10 21:30:42,479][Thread-1:19956][task_id:django.request][log.py:222][WARNING][Not Found: /article/]
[2022-03-10 21:30:43,151][Thread-1:19956][task_id:django.request][log.py:222][WARNING][Not Found: /article/]
[2022-03-10 21:31:21,022][MainThread:19700][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2022-03-10 21:31:22,557][Thread-1:14076][task_id:root][views.py:30][INFO][{'message': '能收到短信吗?', 'phone': '15621435075'}]
[2022-03-10 21:31:29,479][Thread-2:14968][task_id:django.request][log.py:222][WARNING][Not Found: /media/]
[2022-03-10 21:31:37,747][Thread-1:14076][task_id:django.request][log.py:222][WARNING][Not Found: /api/sendMessage/]
[2022-03-10 21:31:43,397][Thread-1:14076][task_id:root][views.py:30][INFO][{'message': '能收到短信吗?', 'phone': '15621435075'}]
